version: '3.8'
services:
    mosquitto:
        image: eclipse-mosquitto:2
        container_name: mosquitto
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./mosquitto/config:/mosquitto/config
            #- ./mosquitto/data:/mosquitto/data
            #- ./mosquitto/log:/mosquitto/log
        networks:
            - mqtt-network
    mqtt-data-generator:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mqtt-data-generator
        depends_on:
            - mosquitto
        networks:
            - mqtt-network
networks:
    mqtt-network:
        driver: bridge
        name: mqtt-network